---
requirement_packages:
  - "acl"
  - "apt-transport-https"
  - "bzip2"
  - "ca-certificates"
  - "curl"
  - "dnsutils"
  - "gnupg"
  - "lsb-release"
  - "software-properties-common"
  - "sshpass"
  - "tree"
  - "unzip"
  - "zip"
