---
- name: "Tap third-party Homebrew repositories"
  community.general.homebrew_tap:
    name: "cirruslabs/cli"
    state: "present"

- name: "Install Homebrew formulae"
  community.general.homebrew:
    name: "{{ homebrew.formulae }}"
    state: "present"

- name: "Install Homebrew casks"
  community.general.homebrew_cask:
    name: "{{ homebrew.casks }}"
    state: "present"

- name: "Install Mac App Store apps"
  community.general.mas:
    id: "{{ item.id }}"
    state: "present"
  loop: "{{ mas_apps }}"
  loop_control:
    label: "{{ item.name }}"
