---
- name: "Create bin directory"
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.local/bin"
    state: "directory"
    mode: "0755"

- name: "Create etc directory"
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.local/etc"
    state: "directory"
    mode: "0755"

- name: "Deploy ansible-pull wrapper script"
  ansible.builtin.template:
    src: "os-setup-pull.sh.j2"
    dest: "{{ ansible_facts.user_dir }}/.local/bin/os-setup-pull.sh"
    mode: "0755"

- name: "Stat secret files"
  ansible.builtin.stat:
    path: "{{ ansible_facts.user_dir }}/.local/etc/{{ item }}"
  register: "secret_files"
  loop:
    - "os-setup.env"
    - "extra_vars.yaml"

- name: "Ensure secret files are mode 0600"
  ansible.builtin.file:
    path: "{{ item.stat.path }}"
    mode: "0600"
    state: "file"
  loop: "{{ secret_files.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: "item.stat.exists"

- name: "Deploy ansible-pull LaunchAgent"
  ansible.builtin.template:
    src: "com.kukv.os-setup.plist.j2"
    dest: "{{ ansible_facts.user_dir }}/Library/LaunchAgents/com.kukv.os-setup.plist"
    mode: "0644"
  notify: "Reload ansible-pull LaunchAgent"

- name: "Check ansible-pull LaunchAgent is loaded"
  ansible.builtin.command:
    cmd: "launchctl list com.kukv.os-setup"
  register: "schedule_loaded"
  changed_when: false
  failed_when: false

- name: "Load ansible-pull LaunchAgent"
  ansible.builtin.command:
    cmd: "launchctl bootstrap gui/{{ ansible_facts.user_uid }} {{ ansible_facts.user_dir }}/Library/LaunchAgents/com.kukv.os-setup.plist"
  when: "schedule_loaded.rc != 0"
