---
- name: "Configure provisioning scheduler (privileged)"
  become: true
  block:
    - name: "Setup ansible log"
      ansible.builtin.include_tasks: "debian_setup_log.yaml"

    - name: "Create systemd unit files"
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - "os-setup.service"
        - "os-setup.timer"
      notify: "Reload systemd"

    - name: "Enable and start provisioning timer"
      ansible.builtin.systemd:
        name: "os-setup.timer"
        enabled: true
        state: "started"

    - name: "Run WSL-specific scheduler configuration"
      ansible.builtin.include_tasks: "wsl.yaml"
      when: "is_wsl"

    - name: "Run native-Linux-specific scheduler configuration"
      ansible.builtin.include_tasks: "linux_native.yaml"
      when: "is_linux_native"
