---
- name: "Restart systemd-resolved"
  become: true
  ansible.builtin.service:
    name: "systemd-resolved"
    state: "restarted"

- name: "Restart systemd-binfmt"
  become: true
  ansible.builtin.service:
    name: "systemd-binfmt"
    state: "restarted"
