---
- name: "Configure OS base (privileged)"
  become: true
  block:
    - name: "Install requirement system packages"
      ansible.builtin.apt:
        name: "{{ requirement_packages }}"
        state: "present"

    - name: "Configure language locale"
      ansible.builtin.include_tasks: "lang_locale_configuration.yaml"

    - name: "Configure time locale"
      ansible.builtin.include_tasks: "time_locale_configuration.yaml"

    - name: "Configure DNS resolver"
      ansible.builtin.include_tasks: "dns_resolver_configuration.yaml"

    - name: "Change default terminal to zsh"
      ansible.builtin.include_tasks: "change_default_terminal.yaml"

    - name: "Run WSL-specific base configuration"
      ansible.builtin.include_tasks: "wsl.yaml"
      when: "is_wsl"

    - name: "Run native-Linux-specific base configuration"
      ansible.builtin.include_tasks: "linux_native.yaml"
      when: "is_linux_native"

- name: "Install Homebrew (Linux)"
  ansible.builtin.include_tasks: "homebrew_bootstrap.yaml"
